2023-08-11 15:22:40,856 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Configure stats pid to 282802
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/.config/wandb/settings
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/dolphin_classification/notebooks/wandb/settings
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_init.py:_log_setup():507] Logging user logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230811_152240-iu6kim3a/logs/debug.log
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_init.py:_log_setup():508] Logging internal logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230811_152240-iu6kim3a/logs/debug-internal.log
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_init.py:init():547] calling init triggers
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'arch': 'InceptionV4'}
2023-08-11 15:22:40,857 INFO    MainThread:282802 [wandb_init.py:init():571] re-initializing run, found existing run on stack: kl9j17r0
2023-08-11 15:22:40,861 INFO    MainThread:282802 [wandb_run.py:_finish():1894] finishing run yashchks87/dolphin/kl9j17r0
2023-08-11 15:22:40,861 INFO    MainThread:282802 [jupyter.py:save_history():445] not saving jupyter history
2023-08-11 15:22:40,861 INFO    MainThread:282802 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-08-11 15:22:40,861 INFO    MainThread:282802 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-08-11 15:22:40,861 INFO    MainThread:282802 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-08-11 15:22:40,862 INFO    MainThread:282802 [wandb_run.py:_restore():2111] restore
2023-08-11 15:22:40,862 INFO    MainThread:282802 [wandb_run.py:_restore():2117] restore done
2023-08-11 15:22:43,720 INFO    MainThread:282802 [wandb_run.py:_footer_history_summary_info():3481] rendering history
2023-08-11 15:22:43,720 INFO    MainThread:282802 [wandb_run.py:_footer_history_summary_info():3513] rendering summary
2023-08-11 15:22:43,727 INFO    MainThread:282802 [wandb_run.py:_footer_sync_info():3440] logging synced files
2023-08-11 15:22:43,828 INFO    MainThread:282802 [wandb_init.py:init():596] starting backend
2023-08-11 15:22:43,829 INFO    MainThread:282802 [wandb_init.py:init():600] setting up manager
2023-08-11 15:22:43,833 INFO    MainThread:282802 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-08-11 15:22:43,834 INFO    MainThread:282802 [wandb_init.py:init():606] backend started and connected
2023-08-11 15:22:43,860 INFO    MainThread:282802 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-08-11 15:22:43,860 INFO    MainThread:282802 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-08-11 15:22:43,860 INFO    MainThread:282802 [wandb_init.py:init():697] updated telemetry
2023-08-11 15:22:43,971 INFO    MainThread:282802 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-11 15:22:44,994 INFO    MainThread:282802 [wandb_run.py:_on_init():2180] communicating current version
2023-08-11 15:22:45,104 INFO    MainThread:282802 [wandb_run.py:_on_init():2189] got version response 
2023-08-11 15:22:45,104 INFO    MainThread:282802 [wandb_init.py:init():781] starting run threads in backend
2023-08-11 15:22:45,216 INFO    MainThread:282802 [wandb_run.py:_console_start():2159] atexit reg
2023-08-11 15:22:45,216 INFO    MainThread:282802 [wandb_run.py:_redirect():2014] redirect: wrap_raw
2023-08-11 15:22:45,216 INFO    MainThread:282802 [wandb_run.py:_redirect():2079] Wrapping output streams.
2023-08-11 15:22:45,216 INFO    MainThread:282802 [wandb_run.py:_redirect():2104] Redirects installed.
2023-08-11 15:22:45,218 INFO    MainThread:282802 [wandb_init.py:init():822] run started, returning control to user process
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Configure stats pid to 282802
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/.config/wandb/settings
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from /home/ubuntu/dolphin_classification/notebooks/wandb/settings
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_init.py:_log_setup():507] Logging user logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230811_154210-59525enx/logs/debug.log
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_init.py:_log_setup():508] Logging internal logs to /home/ubuntu/dolphin_classification/notebooks/wandb/run-20230811_154210-59525enx/logs/debug-internal.log
2023-08-11 15:42:10,199 INFO    MainThread:282802 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3ec7a60f10>
2023-08-11 15:42:10,200 INFO    MainThread:282802 [wandb_init.py:init():547] calling init triggers
2023-08-11 15:42:10,200 INFO    MainThread:282802 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'arch': 'InceptionV4'}
2023-08-11 15:42:10,200 INFO    MainThread:282802 [wandb_init.py:init():571] re-initializing run, found existing run on stack: iu6kim3a
2023-08-11 15:42:10,202 INFO    MainThread:282802 [wandb_run.py:_finish():1894] finishing run yashchks87/dolphin/iu6kim3a
2023-08-11 15:42:10,202 INFO    MainThread:282802 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-08-11 15:42:10,203 INFO    MainThread:282802 [wandb_run.py:_restore():2111] restore
2023-08-11 15:42:10,203 INFO    MainThread:282802 [wandb_run.py:_restore():2117] restore done
2023-08-11 15:42:14,516 INFO    MainThread:282802 [wandb_run.py:_footer_history_summary_info():3481] rendering history
2023-08-11 15:42:14,516 INFO    MainThread:282802 [wandb_run.py:_footer_history_summary_info():3513] rendering summary
2023-08-11 15:42:14,529 INFO    MainThread:282802 [wandb_run.py:_footer_sync_info():3440] logging synced files
